### PR TITLE
add fetchers exports

### PR DESCRIPTION
**Pull request by fpdrozd**
This PR adds exports of createAxiosFetcher and createFetchFetcher functions.

### CODE REVIEW

**Comment by aforty** [comment]
Why was this added? I don't use axios but now that it's exported by default my build breaks because axios isn't available. I was already importing createFetchFetcher and using that, worked great until this commit. In fact there is details in the README about how to use both fetchers so there's really no need to re-export these at index.

**Comment by fpdrozd** [comment]
@aforty Hello! The idea behind this PR was to make the imports of those fetchers look cleaner:
```js
import { createAxiosFetcher } from '@spree/storefront-api-v2-sdk';
```
You are right though, that breaks the separation of fetchers from the main SDK package. For now we are going to revert those changes and in the future we will come up with a better solution for how to handle that (e.g. moving the fetcher functions to separate packages).

**Comment by rafalcymerys** [comment]
@aforty good point, I think we went too far with the changes in exports. 
We'll revert there for now, I think overall we should extract createAxiosFetcher to a separate package, not to rely on axios in the SDK core

**Comment by aforty** [comment]
I think extracting it makes the most sense actually, that's a good idea. Fetch is really good enough for 95% of implementations these days IMHO. Thanks for reverting!

**Comment by rafalcymerys** [comment]
Hi @aforty would be great to hear your thoughts on this PR :) https://github.com/spree/spree-storefront-api-v2-js-sdk/pull/350

**Pull request merged**
